all:
  recaptcha:
    enabled:        false
  vjCommentPlugin:
    guardbind: false
    restricted: false

    recaptcha:
      widget_class:    sfWidgetFormReCaptcha
      validator_class: sfValidatorReCaptcha

    # whether to allow users to "report" bad comments
    enable_comment_reporting: true
    auto_enable_modules:  true     # whether to automatically enable the comment module

    style_web_root:    /vjCommentPlugin/default

    admin_route_prefix: "/admin"

  commentAdmin:
    max_length:     50
  gravatar:
    enabled:        true
    default_size:   40
    default_image:  /vjCommentPlugin/images/gravatar_default.png
