all:
  recaptcha:
    enabled:        false
  vjCommentPlugin:
    guardbind: false
    restricted: false

    auto_enable_modules:  true     # whether to automatically enable the comment module
    enable_comment_reporting: true # whether to allow users to "report" bad comments

    style_web_root:    /vjCommentPlugin/default

  commentAdmin:
    max_length:     50
  gravatar:
    enabled:        true
    default_size:   40
    default_image:  /vjCommentPlugin/images/gravatar_default.png