all:
  recaptcha:
    enabled:        false
  vjCommentPlugin:
    guardbind: false
    restricted: false

    # whether to allow users to "report" bad comments
    enable_comment_reporting: true

    style_web_root:    /vjCommentPlugin/default

  commentAdmin:
    max_length:     50
  gravatar:
    enabled:        true
    default_size:   40
    default_image:  /vjCommentPlugin/images/gravatar_default.png