commentReportSent:
  url: /comment-reported
  param: { module: comment, action: reportSent }

commentReport:
  url: /report-a-comment/:id/:num
  param: { module: comment, action: report }
  requirements:
    id: \d+
    num: \d+

commentReportAdmin:
  class: sfDoctrineRouteCollection
  options:
    model:                CommentReport
    module:               commentReportAdmin
    prefix_path:          <?php echo sfConfig::get('app_vjCommentPlugin_admin_route_prefix', '/admin') ?>/commentReport
    column:               id
    with_wildcard_routes: true

commentAdmin:
  class: sfDoctrineRouteCollection
  options:
    model:                Comment
    module:               commentAdmin
    prefix_path:          <?php echo sfConfig::get('app_vjCommentPlugin_admin_route_prefix', '/admin') ?>/comments
    column:               id
    with_wildcard_routes: true

commentAjaxAdd:
  url: /add-comment
  param: { module: comment, action: add }
  requirements:
    body: .+
    record_model: .+
    record_id: \d+
    user_id: \d+